version: "3.7"
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ".:/dev_local"
    ports:
      - 5000:5000
    environment:
      - PYTHONPATH=/dev_local/
    command: 
      - /usr/local/bin/python
      - src/main.py
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/dev_local"
    ports:
      - 5000:5000
    environment:
      - PYTHONPATH=/dev_local/
    command: 
      - /usr/local/bin/python
      - -m
      - pytest
      - /dev_local/tests/